pipeline:
  data_source: "path/to/raw_data"
  output_path: "data_prep/processed_data.csv"
  log_path: "logs/pipeline.log"


preprocessing_pipeline:

  batch_preprocess_data:
    enabled: true

  lowercase_all_values:
    enabled: true
    
  replace_with_null:
    enabled: true
    params:
      null_vals: ['none', 'empty']

  custom_enforce_types:
    enabled: true
    params:
      per_column:
        int: ['']
        float: ['']
        string: ['city', 'country', 'device_family', 'device_type', 'dma', 'event_id', '']
        datetime: ['']
        
  drop_columns:
    enabled: true
    params:
      columns: ["$insert_id", "$insert_key", "adid", "amplitude_attribution_ids", 
                "amplitude_event_type", "app", "data_type", "device_carrier", 
                "device_brand", "device_manufacturer", "device_model", 
                "global_user_properties", "group_properties", "groups", "idfa", 
                "is_attribution_event", "language", "location_lat", "location_lng", 
                "os_version", "partner_id", "paying", "plan", "platform", 
                "sample_rate", "source_id", "start_version", "user_creation_time", 
                "uuid", "version_name", "data", "$schema"]
  
  fill_missing_values:
    enabled: true
    params:
      strategy: "mean"  # 'available options': "mean", "median", "mode", "constant", ‘forward’, ‘backward’, ‘min’, ‘max’, ‘zero’
      constant_value: null  # use only if strategy = "constant"
  
  encode_categorical:
    enabled: true
    params:
      method: "one_hot"  # 'available options': "one_hot", "label", "ordinal"
      drop_first: true  # if using one-hot encoding, drop first category to avoid collinearity
  
  scale_features:
    enabled: true
    params:
      method:  # 'available options': apply different scalers to different columns
        minmax: ["features name"]
        standard: ["features name"]
        robust: ["features name"]
  
  handle_outliers:
    enabled: true
    params:
      method: "iqr"  # 'available options': "z-score", "iqr", "winsorization"
      threshold: 3  # Z-score threshold, ignored if using IQR
      per_column:  # optional: Different methods for different columns
        feature_1: "z-score"
        feature_2: "winsorization"

  expand_dict_columns:
    enabled : true
    params:
      dict_cols: ['user_properties', 'event_properties']
      include_cols:
        user_properties: ['error', 'element.key', 'route', 'element.props.customAccordion.category', 'element.props.customAccordion.__typename', 
                          '[Amplitude] Page URL', '[Amplitude] Page Path', 'policyId', 'tableId', 'element.props.customAccordion.html', 'items', 
                          'address', 'menu', 'accountType', 'element.props.customAccordion.id', 'internalEmailId', 'name', 'resourceComponent.featureKey', 
                          'referrer', 'quoteName', 'path', 'groupId', 'action', 'formId', 'rowModel', 'templateName', 'element.props.customAccordion.js', 
                          'resourceComponent.ui.defaultVariant', '[Amplitude] Page Title', 'menuVisible', 'isCustomAccordion', 'element.props.name', 'state', 
                          'slug', 'displayName', 'version', 'item', 'resourceComponent.category', 'element.props.customAccordion.title', 'messageId', 'status', 
                          'element.props.isPublishedView', 'rules', '[Amplitude] Page Counter', 'option', 'account-type', 'id', 'element.props.customAccordion.css', 
                          'eventType', 'hasAssignees', 'attachmentId', 'element.props.customAccordion.isPublished', 'policy-id', 'line-of-business', 'referring_domain', 
                          '[Amplitude] Session Replay ID', 'buttonType', 'account-id', 'udoc', 'lineOfBusiness', 'resourceComponent.name', 'variant', 'hasAccounts', 
                          'element.props.customAccordion.accountType', 'accountId', 'type', 'filename', 'element.props.customAccordion.tab', '[Amplitude] Page Domain', 
                          'element.props.customAccordion.meta', 'resourceComponent.featureKeyName', '[Amplitude] Page Location', 'emailId', 'tab']
        
        # event_properties: ['initial_utm_medium', 'initial_li_fat_id', 'initial_gclid', 'trackingVersion', 'initial_utm_id', 'initial_dclid', 'initial_utm_campaign', 
        #                     'initial_ttclid', 'initial_fbclid', 'roles', 'businessUnit', 'initial_gbraid', 'referrer', 'initial_twclid', 'referring_domain', 'initial_utm_term', 
        #                     'initial_msclkid', 'initial_ko_click_id', 'initial_utm_content', 'hostname', 'initial_utm_source', 'initial_wbraid', 'initial_rtd_cid', 'isInternalUser', 
        #                     'initial_referrer', 'bazinga', 'initial_referring_domain']

saving:
  save_processed_data: true
  save_pipeline_state: true
  artifact_path: "artifacts/"
